apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "shortlist-runner.labels" . | nindent 4 }}
  namespace:
spec:
  replicas:
  selector:
    matchLabels:
      app: runner
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "shortlist-runner.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ shorlist-runner.serviceAccountName }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        name: {{ .Chart.Name }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- with .Values.volumeMounts }}
        env:
        - name: ASSESSOR_IMAGE
          value: {{ .Values.assessor_image }}
        - name: NOTIFIER_URL
          value: {{ .Values.notifier_url }}
