apiVersion: v1
kind: Service
metadata:
  name:  {{ include "shortlist-runner.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 8080
  selector:
    {{- include "shortlist-runner.selectorLabels" . | nindent 4 }}
